import "server-only";

// Data access for properties. Reads/writes go through the RLS-scoped client,
// so tenant isolation is enforced by the DB. The plan limit (1 for trial/
// standard, 25 for pro) is enforced by the enforce_property_limit() trigger,
// which raises HG-PROP-403 → recovered by mapPgError. `code` is generated by
// the gen_property_code() trigger, so we never send it on insert.

import { createClient } from "@/lib/supabase/server";
import { ActionResult, ok, mapPgError } from "@/lib/errors";

export interface Property {
  id: string;
  tenant_id: string;
  code: string;
  name: string;
  property_type: "daily" | "monthly" | "both";
  address: string | null;
  city: string | null;
  country: string;
  currency: string;
  timezone: string;
  // billing settings (migration 08) — used by the accounting module
  legal_name: string | null;
  tax_id: string | null;
  billing_address: string | null;
  vat_rate: number;
  vat_inclusive: boolean;
  bank_name: string | null;
  bank_account: string | null;
  invoice_prefix: string;
  invoice_footer: string | null;
  created_at: string;
}

export interface CreatePropertyInput {
  tenant_id: string;
  name: string;
  property_type: "daily" | "monthly" | "both";
  address?: string;
  city?: string;
  country?: string;
  currency?: string;
  timezone?: string;
}

/** All properties visible to the current user (RLS-scoped), newest tenants first. */
export async function listProperties(): Promise<ActionResult<Property[]>> {
  try {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("properties")
      .select("*")
      .order("created_at", { ascending: true });
    if (error) throw error;
    return ok((data ?? []) as Property[]);
  } catch (e) {
    return mapPgError(e);
  }
}

/** Create a property. The trigger raises HG-PROP-403 when over the plan limit. */
export async function createProperty(
  input: CreatePropertyInput
): Promise<ActionResult<Property>> {
  try {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("properties")
      .insert({
        tenant_id: input.tenant_id,
        name: input.name,
        property_type: input.property_type,
        address: input.address ?? null,
        city: input.city ?? null,
        country: input.country ?? "TH",
        currency: input.currency ?? "THB",
        timezone: input.timezone ?? "Asia/Bangkok",
      })
      .select()
      .single();
    if (error) throw error;
    return ok(data as Property);
  } catch (e) {
    return mapPgError(e);
  }
}

/** Patch a property's editable fields. tenant_id/code/id are not patchable here. */
export async function updateProperty(
  id: string,
  patch: Partial<Omit<Property, "id" | "tenant_id" | "code" | "created_at">>
): Promise<ActionResult<Property>> {
  try {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("properties")
      .update(patch)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return ok(data as Property);
  } catch (e) {
    return mapPgError(e);
  }
}
